export const products = [
  {
    id: 1,
    name: "Nike Shoes",
    category: "Footwear",
    price: 99.99,
    badge: "Sale",
    image: "/nike-shoes.jpg",
    width: 400,
    height: 250,
  },
  {
    id: 2,
    name: "Adidas Sneakers",
    category: "Footwear",
    price: 29.99,
    badge: null,
    image: "/adidas-sneakers.jpg",
    width: 400,
    height: 250,
  },
  {
    id: 3,
    name: "Apple Watch",
    category: "Electronics",
    price: 199.99,
    badge: "New",
    image: "/apple-watch.jpg",
    width: 400,
    height: 250,
  },
  {
    id: 4,
    name: "Samsung TV",
    category: "Electronics",
    price: 499.99,
    badge: null,
    image: "/samsung-tv.jpg",
    width: 400,
    height: 250,
  },
];
